[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "dotnet restore MusicWebAPI/MusicWebAPI.API.csproj",
  "dotnet build MusicWebAPI/MusicWebAPI.API.csproj -c Release",
  "dotnet publish MusicWebAPI/MusicWebAPI.API.csproj -c Release -o publish"
]

[start]
cmd = "dotnet MusicWebAPI.API.dll"
workingDir = "publish"
