version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - musicnet
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sa"]
      interval: 10s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: MusicWebAPI/Dockerfile
    container_name: musicwebapi_container
    ports:
      - "8080:8080"
    networks:
      - musicnet
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__MusicDbConnection=${ConnectionStrings__MusicDbConnection}
      - JwtSettings__SecretKey=${JwtSettings__SecretKey}
      - JwtSettings__Issuer=${JwtSettings__Issuer}
      - JwtSettings__Audience=${JwtSettings__Audience}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local
  data_protection_keys:
    driver: local

networks:
  musicnet:
    driver: bridge
