//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWebAPI.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicWebAPI.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have an active plan!.
        /// </summary>
        public static string AlreadySubscribedError {
            get {
                return ResourceManager.GetString("AlreadySubscribedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string ArtistRole {
            get {
                return ResourceManager.GetString("ArtistRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song already exists in the playlist..
        /// </summary>
        public static string DuplicateSongInPlaylist {
            get {
                return ResourceManager.GetString("DuplicateSongInPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email or username already exists!.
        /// </summary>
        public static string DuplicateUserError {
            get {
                return ResourceManager.GetString("DuplicateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found!.
        /// </summary>
        public static string FileNotExists {
            get {
                return ResourceManager.GetString("FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Password Reset Verification&lt;/h2&gt;
        ///&lt;p&gt;Hello,&lt;/p&gt;
        ///&lt;p&gt;You requested to reset your password. Please use the following OTP code to verify your identity:&lt;/p&gt;
        ///&lt;h3 style=&quot;color: #2e6da4;&quot;&gt;{0}&lt;/h3&gt;
        ///&lt;p&gt;This code is valid for 10 minutes.&lt;/p&gt;
        ///
        ///&lt;p&gt;You can also reset your password directly by clicking the link below:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;{1}&quot; style=&quot;color: #2e6da4;&quot;&gt;Reset your password&lt;/a&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;If you did not request this, please ignore this email.&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;Thanks,&lt;br/&gt;The Support Team&lt;/p&gt;
        ///.
        /// </summary>
        public static string ForgetPassEmailBody {
            get {
                return ResourceManager.GetString("ForgetPassEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again later..
        /// </summary>
        public static string GeneralUnhandledError {
            get {
                return ResourceManager.GetString("GeneralUnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popular_songs_.
        /// </summary>
        public static string GetPopularSongs_CacheKey {
            get {
                return ResourceManager.GetString("GetPopularSongs_CacheKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search_songs_.
        /// </summary>
        public static string GetSongsByTerm_CacheKey {
            get {
                return ResourceManager.GetString("GetSongsByTerm_CacheKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Password is not correct! Try again..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidGoogleToken!.
        /// </summary>
        public static string InvalidGoogleToken {
            get {
                return ResourceManager.GetString("InvalidGoogleToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid plan!.
        /// </summary>
        public static string InvalidPlan {
            get {
                return ResourceManager.GetString("InvalidPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Range header1.
        /// </summary>
        public static string InvalidRangeHeader {
            get {
                return ResourceManager.GetString("InvalidRangeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListenCount:{0}:{1}:{2}.
        /// </summary>
        public static string ListenCountCacheKey {
            get {
                return ResourceManager.GetString("ListenCountCacheKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to otp_.
        /// </summary>
        public static string OtpCode_CacheKey {
            get {
                return ResourceManager.GetString("OtpCode_CacheKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be 8 or more than 8 characters!.
        /// </summary>
        public static string PasswordMin {
            get {
                return ResourceManager.GetString("PasswordMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should contain every type of characters!.
        /// </summary>
        public static string PasswordQuality {
            get {
                return ResourceManager.GetString("PasswordQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should contain special characters!.
        /// </summary>
        public static string PasswordUnique {
            get {
                return ResourceManager.GetString("PasswordUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no PlatList with this Id!.
        /// </summary>
        public static string PlaylistNotFound {
            get {
                return ResourceManager.GetString("PlaylistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no song in related Playlist with that SongName!.
        /// </summary>
        public static string PlaylistSongNotFound {
            get {
                return ResourceManager.GetString("PlaylistSongNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset failed!.
        /// </summary>
        public static string ResetPasswordError {
            get {
                return ResourceManager.GetString("ResetPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song not found!.
        /// </summary>
        public static string SongNotFound {
            get {
                return ResourceManager.GetString("SongNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream limit reached. Please wait for your 12-hour window to reset or consider subscribing to our premium plan for unlimited access..
        /// </summary>
        public static string SongStreamLimitError {
            get {
                return ResourceManager.GetString("SongStreamLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription not found!.
        /// </summary>
        public static string SubscriptionNotFound {
            get {
                return ResourceManager.GetString("SubscriptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperUser.
        /// </summary>
        public static string SuperUserRole {
            get {
                return ResourceManager.GetString("SuperUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should authorize first!.
        /// </summary>
        public static string UnAuthorizedError {
            get {
                return ResourceManager.GetString("UnAuthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has not found!.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration failed!.
        /// </summary>
        public static string UserRegistrationError {
            get {
                return ResourceManager.GetString("UserRegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not acquire payment verification lock. Please retry..
        /// </summary>
        public static string SubscriptionRedisLockError {
            get {
                return ResourceManager.GetString("VerifyPaymentRedisLockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered wrong or expired OTP code!.
        /// </summary>
        public static string WrongOtpCodeError {
            get {
                return ResourceManager.GetString("WrongOtpCodeError", resourceCulture);
            }
        }
    }
}
