//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWebAPI.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicWebAPI.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string ArtistRole {
            get {
                return ResourceManager.GetString("ArtistRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song already exists in the playlist..
        /// </summary>
        public static string DuplicateSongInPlaylist {
            get {
                return ResourceManager.GetString("DuplicateSongInPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email or username already exists!.
        /// </summary>
        public static string DuplicateUserError {
            get {
                return ResourceManager.GetString("DuplicateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found!.
        /// </summary>
        public static string FileNotExists {
            get {
                return ResourceManager.GetString("FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again later..
        /// </summary>
        public static string GeneralUnhandledErrorText {
            get {
                return ResourceManager.GetString("GeneralUnhandledErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popular_songs_.
        /// </summary>
        public static string GetPopularSongs_CacheKey {
            get {
                return ResourceManager.GetString("GetPopularSongs_CacheKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search_songs_.
        /// </summary>
        public static string GetSongsByTerm_CacheKey {
            get {
                return ResourceManager.GetString("GetSongsByTerm_CacheKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Password is not correct! Try again..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Range header1.
        /// </summary>
        public static string InvalidRangeHeader {
            get {
                return ResourceManager.GetString("InvalidRangeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be 8 or more than 8 characters!.
        /// </summary>
        public static string PasswordMin {
            get {
                return ResourceManager.GetString("PasswordMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should contain every type of characters!.
        /// </summary>
        public static string PasswordQuality {
            get {
                return ResourceManager.GetString("PasswordQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should contain special characters!.
        /// </summary>
        public static string PasswordUnique {
            get {
                return ResourceManager.GetString("PasswordUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no PlatList with this Id!.
        /// </summary>
        public static string PlaylistNotFound {
            get {
                return ResourceManager.GetString("PlaylistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no song in related Playlist with that SongName!.
        /// </summary>
        public static string PlaylistSongNotFound {
            get {
                return ResourceManager.GetString("PlaylistSongNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song not found!.
        /// </summary>
        public static string SongNotFound {
            get {
                return ResourceManager.GetString("SongNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperUser.
        /// </summary>
        public static string SuperUserRole {
            get {
                return ResourceManager.GetString("SuperUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has not found!.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration failed!.
        /// </summary>
        public static string UserRegistrationError {
            get {
                return ResourceManager.GetString("UserRegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
    }
}
